AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  CloudFormation template to create an Amazon EventBridge rule 
  that triggers an existing Lambda function for monthly DynamoDB backups 
  on the 29th of each month at 14:05 JST (05:05 UTC).

Parameters:
  ExistingLambdaFunctionArn: # パラメータ名を変更し、既存のLambda ARNを受け取る
    Type: String
    Description: The ARN of the existing Lambda function to be triggered.
    # 例: arn:aws:lambda:ap-northeast-1:123456789012:function:DynamoDBPITRtoS3Export
  ScheduleCronExpression:
    Type: String
    Description: >-
      UTC Cron expression for the schedule. 
      Default is 'cron(5 5 29 * ? *)' for 05:05 AM UTC on the 29th of every month (14:05 JST).
    Default: 'cron(5 5 29 * ? *)' # 毎月29日 05:05 UTC (JST 14:05)
  EventRuleName:
    Type: String
    Description: A name for the EventBridge rule.
    Default: TriggerDynamoDBMonthlyBackupLambdaRule # ルール名をより具体的に変更
  TargetId:
    Type: String
    Description: A unique ID for the target (Lambda function) within the rule.
    Default: MonthlyBackupLambdaTarget # ターゲットIDをシンプルに

Resources:
  BackupEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Ref EventRuleName
      Description: !Sub 'Triggers Lambda ${ExistingLambdaFunctionArn} for DynamoDB backup on the 29th of each month at 14:05 JST (05:05 UTC).'
      ScheduleExpression: !Ref ScheduleCronExpression
      State: ENABLED
      Targets:
        - Arn: !Ref ExistingLambdaFunctionArn # パラメータで渡された既存LambdaのARNを使用
          Id: !Ref TargetId

  BackupEventRulePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ExistingLambdaFunctionArn # パラメータで渡された既存LambdaのARN（または名前）を使用
      Principal: events.amazonaws.com
      SourceArn: !GetAtt BackupEventRule.Arn

Outputs:
  EventRuleName: # Outputsのキー名をシンプルにしました
    Description: The name of the created EventBridge rule.
    Value: !Ref BackupEventRule
  EventRuleArn: # ARNも出力
    Description: The ARN of the created EventBridge rule.
    Value: !GetAtt BackupEventRule.Arn
